from typing import Protocol
from datetime import datetime
from .models import Appointment, ScheduleClosure, SpaceSchedule, TreatmentCourse, TreatmentSlot

class AppointmentRepository(Protocol):
    def get_by_id(self, appointment_id: int) -> Appointment | None:...
    def get_course_appointments(self, course_id: int) -> list[Appointment]: ...
    def get_planned_course_appointments(self, course_id: int) -> list[Appointment]: ...
    def save(self, appointment: Appointment) -> Appointment: ...
    def cancel(self, appointment_id: int) -> None: ...

class CourseRepository(Protocol):
    def get_by_id(self, course_id: int) -> TreatmentCourse | None: ...
    def get_active_course_by_patient_id(self, patient_id: int) -> TreatmentCourse | None: ...
    def cancel(self, course_id: int) -> None: ...
    def save(self, slot: TreatmentCourse) -> TreatmentCourse: ...

class SlotRepository(Protocol):
    def get_by_id(self, slot_id: int) -> TreatmentSlot | None: ...
    def get_booked_in_range(self, space_id: int, start: datetime, end: datetime) -> list[TreatmentSlot]: ... #Should return all booked slots between given dates 
    def unbook(self, slot_id: int) -> Appointment | None:... #Should return the appointment at the given slot being unbooked, deletes the timeslot
    def save(self, slot: TreatmentSlot) -> TreatmentSlot: ...

class ScheduleRepository(Protocol):
    def get_rules_for_space(self, space_id: int) -> list[SpaceSchedule]: ...
    def get_closures(self, start: datetime, end: datetime) -> list[ScheduleClosure]: ...