from typing import Protocol
from datetime import datetime
from .models import Appointment, TreatmentCourse, TreatmentSlot

class AppointmentRepository(Protocol):
    def get_by_id(self, appointment_id: int) -> Appointment | None:...
    def save(self, appointment: Appointment) -> Appointment: ...
    def cancel(self, appointment_id: int) -> None: ...

class CourseRepository(Protocol):
    def get_by_id(self, course_id: int) -> TreatmentCourse: ...
    def get_course_appointments(self, course_id: int) -> list[Appointment]: ...
    def get_planned_course_appointments(self, course_id: int) -> list[Appointment]: ...
    def get_active_course_by_patient_id(self, patient_id: int) -> TreatmentCourse: ...
    def cancel(self, course_id: int) -> None: ...
    #Might need a save method

class SlotRepository(Protocol):
    def get_by_id(self, slot_id: int) -> TreatmentSlot: ...
    def get_by_date(self, date: datetime) -> list[TreatmentSlot]: ...
    def get_free_by_date(self, date: datetime) -> list[TreatmentSlot]: ...
    def unbook(self, slot_id: int) -> Appointment | None:... #Should return the appointment at the given slot being unbooked
    def save(self, slot: TreatmentSlot) -> TreatmentSlot: ...
