# Generated by Django 6.0.6 on 2026-08-21 20:05

import django.contrib.postgres.constraints
import django.db.models.deletion
import django.utils.timezone
import infra.validators.cpr
from django.db import migrations, models
from django.contrib.postgres.operations import BtreeGistExtension

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_number', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=60)),
                ('gender', models.IntegerField(choices=[(1, 'Mand'), (2, 'Kvinde'), (3, 'Ikke tildelt')], default=3)),
                ('CPR_number', models.CharField(db_index=True, max_length=10, unique=True, validators=[infra.validators.cpr.validate_cpr])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentSpace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_treatments', models.SmallIntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'Planlagt'), (2, 'Igangværende'), (3, 'Fuldført'), (4, 'Aflyst')], default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infra.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(db_index=True)),
                ('end_time', models.DateTimeField()),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.treatmentspace')),
            ],
        ),
        migrations.CreateModel(
            name='SpaceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Man'), (1, 'Tir'), (2, 'Ons'), (3, 'Tor'), (4, 'Fre'), (5, 'Lør'), (6, 'Søn')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infra.treatmentspace')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infra.treatmentspace')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('space', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infra.treatmentspace')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment_number', models.SmallIntegerField()),
                ('treatment_type', models.IntegerField(choices=[(1, 'V1'), (2, 'V2')], default=1)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('status', models.IntegerField(choices=[(1, 'Planlagt'), (2, 'Fuldført'), (3, 'Aflyst'), (4, 'Udeblevet')], default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='infra.treatmentcourse')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='infra.treatmentslot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('course', 'treatment_number'), name='unique_active_course_treatment_number')],
            },
        ),
        migrations.AddConstraint(
            model_name='treatmentslot',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(expressions=[('space', '='), (models.Func('start_time', 'end_time', function='tstzrange'), '&&')], name='no_overlapping_slots_per_space'),
        ),
        migrations.AlterUniqueTogether(
            name='spaceschedule',
            unique_together={('space', 'weekday')},
        ),
    ]
