# Generated by Django 6.0.6 on 2026-08-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0003_patient_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_number',
            field=models.PositiveIntegerField(editable=False, unique=True),
        ),
    ]
