# Generated by Django 6.0.6 on 2026-08-25 19:39

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0004_patient_number2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_number',
            field=models.PositiveIntegerField(db_default=django.db.models.expressions.RawSQL("nextval('infra_patient_number_seq')", []), editable=False, unique=True),
        ),
    ]
