# Generated by Django 6.0.6 on 2026-09-30 19:06

import django.contrib.postgres.constraints
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra', '0005_patient_number3'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='treatmentslot',
            name='no_overlapping_slots_per_space',
        ),
        migrations.AddField(
            model_name='treatmentslot',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='treatmentslot',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('is_active', True)), expressions=[('space', '='), (models.Func('start_time', 'end_time', function='tstzrange'), '&&')], name='no_overlapping_active_slots_per_space'),
        ),
    ]
