from typing import Protocol
from .models import PatientDetail


class PatientRepository(Protocol):
    def get_by_cpr(self, cpr: str) -> PatientDetail | None: ...
    def save(self, patient: PatientDetail) -> PatientDetail: ...
    def reactivate(self, patient_id: int) -> PatientDetail: ...
    def get_by_id(self, patient_id: str) -> PatientDetail | None: ...
    def get_active_patients(self) -> list[PatientDetail]: ...